/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elsewedytask.View;

import elsewedytask.Controller.ImportFileController;
import elsewedytask.Controller.MaterialSetController;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author SAM
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        JtableExcelFile.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jPanelSet2.hide();
        jPanelSet3.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableExcelFile = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanelSetsBase = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jPanelSet1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListM1 = new javax.swing.JList<>();
        jButtonRemove1 = new javax.swing.JButton();
        jCheckBoxMainSet = new javax.swing.JCheckBox();
        jLabelSum1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldS1 = new javax.swing.JTextField();
        jPanelSet3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListM3 = new javax.swing.JList<>();
        jButtonRemove3 = new javax.swing.JButton();
        jCheckBoxSet3 = new javax.swing.JCheckBox();
        jLabelSum3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFields3 = new javax.swing.JTextField();
        jPanelSet2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListM2 = new javax.swing.JList<>();
        jButtonRemove2 = new javax.swing.JButton();
        jCheckBoxSet2 = new javax.swing.JCheckBox();
        jLabelSum2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldS2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/Elswedy_logo.png"))); // NOI18N
        jPanel1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        JtableExcelFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JtableExcelFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(JtableExcelFile);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imported Excel File");

        jPanelSetsBase.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/add_20px.png"))); // NOI18N
        jButton2.setText("Add Material");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/saveSets_30px.png"))); // NOI18N
        jButton3.setText("Save Sets");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanelSet1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSet1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("SET 1");

        jListM1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListM1);

        jButtonRemove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/Remove_20px.png"))); // NOI18N
        jButtonRemove1.setText("Remove");
        jButtonRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemove1ActionPerformed(evt);
            }
        });

        jCheckBoxMainSet.setSelected(true);
        jCheckBoxMainSet.setText("In Selection");

        jLabelSum1.setText("0");

        jLabel11.setText("Sum: ");

        jLabel4.setText("Name:");

        jTextFieldS1.setText("MSet1");

        javax.swing.GroupLayout jPanelSet1Layout = new javax.swing.GroupLayout(jPanelSet1);
        jPanelSet1.setLayout(jPanelSet1Layout);
        jPanelSet1Layout.setHorizontalGroup(
            jPanelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSet1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet1Layout.createSequentialGroup()
                        .addComponent(jButtonRemove1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSum1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldS1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxMainSet, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSet1Layout.setVerticalGroup(
            jPanelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSet1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxMainSet)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemove1)
                    .addComponent(jLabelSum1)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSet3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSet3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("SET 3");

        jListM3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListM3);

        jButtonRemove3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/Remove_20px.png"))); // NOI18N
        jButtonRemove3.setText("Remove");
        jButtonRemove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemove3ActionPerformed(evt);
            }
        });

        jCheckBoxSet3.setText("In Selection");

        jLabelSum3.setText("0");

        jLabel13.setText("Sum: ");

        jLabel9.setText("Name:");

        jTextFields3.setText("MSet3");

        javax.swing.GroupLayout jPanelSet3Layout = new javax.swing.GroupLayout(jPanelSet3);
        jPanelSet3.setLayout(jPanelSet3Layout);
        jPanelSet3Layout.setHorizontalGroup(
            jPanelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSet3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet3Layout.createSequentialGroup()
                        .addComponent(jButtonRemove3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSum3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFields3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxSet3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSet3Layout.setVerticalGroup(
            jPanelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSet3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBoxSet3)
                    .addComponent(jLabel9)
                    .addComponent(jTextFields3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemove3)
                    .addComponent(jLabelSum3)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSet2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSet2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("SET 2");

        jListM2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jListM2);

        jButtonRemove2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/Remove_20px.png"))); // NOI18N
        jButtonRemove2.setText("Remove");
        jButtonRemove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemove2ActionPerformed(evt);
            }
        });

        jCheckBoxSet2.setText("In Selection");

        jLabelSum2.setText("0");

        jLabel12.setText("Sum:");

        jLabel10.setText("Name:");

        jTextFieldS2.setText("MSet2");
        jTextFieldS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSet2Layout = new javax.swing.GroupLayout(jPanelSet2);
        jPanelSet2.setLayout(jPanelSet2Layout);
        jPanelSet2Layout.setHorizontalGroup(
            jPanelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSet2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet2Layout.createSequentialGroup()
                        .addComponent(jButtonRemove2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSum2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSet2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldS2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxSet2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSet2Layout.setVerticalGroup(
            jPanelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSet2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBoxSet2)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemove2)
                    .addComponent(jLabelSum2)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/icons8_toggle_off_20px.png"))); // NOI18N
        jToggleButton1.setText("Show More Sets");
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/icons8_toggle_on_20px.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSetsBaseLayout = new javax.swing.GroupLayout(jPanelSetsBase);
        jPanelSetsBase.setLayout(jPanelSetsBaseLayout);
        jPanelSetsBaseLayout.setHorizontalGroup(
            jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1))
                            .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                                .addComponent(jPanelSet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelSet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                                        .addComponent(jPanelSet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 279, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanelSetsBaseLayout.setVerticalGroup(
            jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSetsBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                        .addComponent(jPanelSet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanelSetsBaseLayout.createSequentialGroup()
                        .addGroup(jPanelSetsBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelSetsBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSetsBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elsewedytask/Assets/ExcelIco_30px.png"))); // NOI18N
        jButton1.setText("Import Excel File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getJtableExcelFile() {
        return JtableExcelFile;
    }

    public void setJtableExcelFile(JTable JtableExcelFile) {
        this.JtableExcelFile = JtableExcelFile;
    }

    public JCheckBox getjCheckBoxMainSet() {
        return jCheckBoxMainSet;
    }

    public void setjCheckBoxMainSet(JCheckBox jCheckBoxMainSet) {
        this.jCheckBoxMainSet = jCheckBoxMainSet;
    }

    public JCheckBox getjCheckBoxSet2() {
        return jCheckBoxSet2;
    }

    public void setjCheckBoxSet2(JCheckBox jCheckBoxSet2) {
        this.jCheckBoxSet2 = jCheckBoxSet2;
    }

    public JCheckBox getjCheckBoxSet3() {
        return jCheckBoxSet3;
    }

    public void setjCheckBoxSet3(JCheckBox jCheckBoxSet3) {
        this.jCheckBoxSet3 = jCheckBoxSet3;
    }

    public JList<String> getjListM1() {
        return jListM1;
    }

    public void setjListM1(JList<String> jListM1) {
        this.jListM1 = jListM1;
    }

    public JList<String> getjListM2() {
        return jListM2;
    }

    public void setjListM2(JList<String> jListM2) {
        this.jListM2 = jListM2;
    }

    public JList<String> getjListM3() {
        return jListM3;
    }

    public void setjListM3(JList<String> jListM3) {
        this.jListM3 = jListM3;
    }

    public void setjLabelSum1(JLabel jLabelSum1) {
        this.jLabelSum1 = jLabelSum1;
    }

    public void setjLabelSum2(JLabel jLabelSum2) {
        this.jLabelSum2 = jLabelSum2;
    }

    public void setjLabelSum3(JLabel jLabelSum3) {
        this.jLabelSum3 = jLabelSum3;
    }

    public JLabel getjLabelSum1() {
        return jLabelSum1;
    }

    public JLabel getjLabelSum2() {
        return jLabelSum2;
    }

    public JLabel getjLabelSum3() {
        return jLabelSum3;
    }

    public JTextField getjTextFieldS1() {
        return jTextFieldS1;
    }

    public void setjTextFieldS1(JTextField jTextFieldS1) {
        this.jTextFieldS1 = jTextFieldS1;
    }

    public JTextField getjTextFieldS2() {
        return jTextFieldS2;
    }

    public void setjTextFieldS2(JTextField jTextFieldS2) {
        this.jTextFieldS2 = jTextFieldS2;
    }

    public JTextField getjTextFields3() {
        return jTextFields3;
    }

    public void setjTextFields3(JTextField jTextFields3) {
        this.jTextFields3 = jTextFields3;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImportFileController importExcel = new ImportFileController(this);
        importExcel.getExcelFromFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MaterialSetController materialSetController = MaterialSetController.getInstance(); //Singleton
        materialSetController.handleSelectedRowToSet(this);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemove1ActionPerformed
        // TODO add your handling code here:
        MaterialSetController controller = MaterialSetController.getInstance();
        controller.removeElmentFromJlistModal(jListM1, 0);
        jLabelSum1.setText(controller.getArrayListMaterialSets().get(0).getTotalQuantity() + "");

    }//GEN-LAST:event_jButtonRemove1ActionPerformed

    private void jButtonRemove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemove2ActionPerformed
        // TODO add your handling code here:
        MaterialSetController controller = MaterialSetController.getInstance();
        controller.removeElmentFromJlistModal(jListM2, 1);
        jLabelSum1.setText(controller.getArrayListMaterialSets().get(1).getTotalQuantity() + "");

    }//GEN-LAST:event_jButtonRemove2ActionPerformed

    private void jButtonRemove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemove3ActionPerformed
        // TODO add your handling code here:
        MaterialSetController controller = MaterialSetController.getInstance();
        controller.removeElmentFromJlistModal(jListM3, 2);
        jLabelSum1.setText(controller.getArrayListMaterialSets().get(2).getTotalQuantity() + "");

    }//GEN-LAST:event_jButtonRemove3ActionPerformed

    private void jTextFieldS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldS2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MaterialSetController controller = MaterialSetController.getInstance();
        controller.saveToDBMaterialSet();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (!jToggleButton1.isSelected()) {
            jPanelSet2.hide();
            jPanelSet3.hide();
            jCheckBoxSet2.setSelected(false);
            jCheckBoxSet3.setSelected(false);
        } else {
            jPanelSet2.show();
            jPanelSet3.show();
        }
        jPanelSetsBase.repaint();
        jPanelSetsBase.revalidate();
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableExcelFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRemove1;
    private javax.swing.JButton jButtonRemove2;
    private javax.swing.JButton jButtonRemove3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBoxMainSet;
    private javax.swing.JCheckBox jCheckBoxSet2;
    private javax.swing.JCheckBox jCheckBoxSet3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSum1;
    private javax.swing.JLabel jLabelSum2;
    private javax.swing.JLabel jLabelSum3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jListM1;
    private javax.swing.JList<String> jListM2;
    private javax.swing.JList<String> jListM3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSet1;
    private javax.swing.JPanel jPanelSet2;
    private javax.swing.JPanel jPanelSet3;
    private javax.swing.JPanel jPanelSet4;
    private javax.swing.JPanel jPanelSet5;
    private javax.swing.JPanel jPanelSetsBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldS1;
    private javax.swing.JTextField jTextFieldS2;
    private javax.swing.JTextField jTextFields3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
